### ISSUE TITLE
Installation does not work on 3.0.19, breaks engine daemon

### ISSUE THREAD

**Issue by fightforlife** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#11]
I just tried installing this plugin on OMW 3.0.19 and the installation script runs fine, but after restarting the engine daemon nothing is working anymore.
The engine daemon wont startup anymore. 

Failure log following...

**Comment by ryecoaaron** [comment]
The plugin hasn't been ported to the new data models introduced in 3.0.15.  No need to post a failure log.

**Comment by imgrant** [comment]
Thanks for the report, though. I will update the plugin once OMV 3 is final/feature complete/stable.
