### ISSUE TITLE
"Create encyption" should offer partitions (/dev/sda1) not only the entire disk (/dev/sda)

### ISSUE THREAD

**Issue by getreu** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#12]
It is also possible to create a RAID directly on the raw disks (without partitions), but not recommended because it can cause problems when swapping a failed disk.
When replacing a failed disk of a RAID, the new disk has to be exactly the same size as the failed disk or bigger — otherwise the array recreation process will not work. Even hard drives of the same manufacturer and model can have small size differences. By leaving a little space at the end of the disk unallocated one can compensate for the size differences between drives, which makes choosing a replacement drive model easier. Therefore, it is good practice to leave about 100 MB of unallocated space at the end of the disk. Therefore "create encryption" should operate on partitions e.g. /dev/sda1 not entire disks e.g. /dev/sda.

**Comment by imgrant** [comment]
This is a good point, but only applicable to RAID arrays, not LUKS. It could be a problem if you do RAID-on-LUKS, but this is not recommended. It is better to do LUKS-on-RAID, in which case, you will not have this problem. For this reason, I don't see this as a high priority to change.

**Comment by luksomv** [comment]
This feature is **HIGHLY** needed!

There are several devices which are capable running OMV and just have the capability of one drive (Buffalo NAS, WD NAD, *Plug Devices, and many more running Debian). Since your OMV Plugin went public it gave me the opportunity to finally use OMV with encryption (which is badly needed!)

I have several "one-disk"-solution and I can not setup the encryption because the drive has a couple of partitions (including the root-filesystem of omv). Even one partition with 5.8TB is empty I can't use it! To bad!

_Hope for this coming true some time..._

**Comment by luksomv** [comment]
Just to let you know:
I created a LUKS+ext4 over my empty data partition. I can unlock and mount it on my workstation. When I try to get it recognized within OMV it doesn't work. Not within the Encryption Tab and nether in the File Systems Tab.

**Comment by imgrant** [comment]
The rest of OMV does not operate with partitions like this, a data partition on the OS drive is unsupported in OMV, though you can do it via the command line. My initial feeling is to take the same line with this plugin too. Having said that, it should then work with existing partitions created via the command line, I will have to test it out myself to verify; I wouldn't expect to see the problems you describe.

**Comment by luksomv** [comment]
It works like you described. It's possible to mount all kind of LUKS drives/raids/partition. Just the creation is limited!

More here: http://forums.openmediavault.org/index.php/Thread/11592-LUKS-disk-encryption-plugin/?postID=117856#post117856

**Comment by getreu** [comment]
> It works like you described. It's possible to mount all kind of LUKS drives/raids/partition. Just the creation is limited!
I can confirm. BTW: the same also applies to Raid generation! As Raid management is not a plugin where to file a request?

**Comment by davidh2k** [comment]
You can request core changes at http://bugtracker.openmediavault.org

Von meinem iPhone gesendet
