### ISSUE TITLE
Missing busybox dependency?

### ISSUE THREAD

**Issue by kratz00** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#16]
Environment:
* Debian 9
* OMV 4 (4.1.0)
* armv7l

I had trouble installing this plugin, from the logs:
``
sudo apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-luksencryption
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  cryptsetup cryptsetup-bin
Recommended packages:
  busybox | busybox-static
The following NEW packages will be installed:
  cryptsetup cryptsetup-bin openmediavault-luksencryption
0 upgraded, 3 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/435 kB of archives.
After this operation, 1,830 kB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package cryptsetup-bin.
(Reading database ... 47109 files and directories currently installed.)
Preparing to unpack .../cryptsetup-bin_2%3a1.7.3-4_armhf.deb ...
Unpacking cryptsetup-bin (2:1.7.3-4) ...
Selecting previously unselected package cryptsetup.
Preparing to unpack .../cryptsetup_2%3a1.7.3-4_armhf.deb ...
Unpacking cryptsetup (2:1.7.3-4) ...
Selecting previously unselected package openmediavault-luksencryption.
Preparing to unpack .../openmediavault-luksencryption_3.0.2_all.deb ...
Unpacking openmediavault-luksencryption (3.0.2) ...
Processing triggers for systemd (232-25+deb9u2) ...
Setting up cryptsetup-bin (2:1.7.3-4) ...
Processing triggers for man-db (2.7.6.1-2) ...
Processing triggers for openmediavault (4.1.0-1) ...
Restarting engine daemon ...
Setting up cryptsetup (2:1.7.3-4) ...
update-initramfs: deferring update (trigger activated)
insserv: Service checkroot has to be enabled to start service cryptdisks-early
insserv: Service checkroot has to be enabled to start service cryptdisks
Setting up openmediavault-luksencryption (3.0.2) ...
Processing triggers for initramfs-tools (0.130) ...
update-initramfs: Generating /boot/initrd.img-4.14.20-mvebu
E: busybox or busybox-static, version 1:1.22.0-17~ or later, is required but not installed
update-initramfs: failed for /boot/initrd.img-4.14.20-mvebu with 1.
dpkg: error processing package initramfs-tools (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for openmediavault (4.1.0-1) ...
Updating locale files ...
Updating file permissions ...
Purging internal cache ...
Restarting engine daemon ...
Errors were encountered while processing:
 initramfs-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)
``
After installing busybox I ran the install command again and it succeeded this time

**Comment by kratz00** [comment]
Here is the log in a more readable form: https://gist.github.com/kratz00/c4558e4cf9275a8c2e0480cb4e884ca8

**Comment by subzero79** [comment]
None of the above packages pulls busybox as a dependency. The default rpi image and other arm images brewed for omv do not come with busybox. The debian cryptsetup package however recommends busybox. This comes by default in x86 installs (i think). 

I think is better to add this in the images instead of the plugin dependencies in a similar way as happens with x86 machines. See if you can post here https://forum.openmediavault.org/index.php/Thread/18991-New-approach-for-Raspberry-Pi-OMV-images/?postID=170148&highlight=raspberry%2Bpi#post170148
to request it.

**Comment by subzero79** [comment]
Sorry forgot to ask you if this was a rpi or other ARM device?

**Comment by kratz00** [comment]
@subzero79 I see, thanks for the explanation.
The device is a Helios4 (Marvell ARMADA 388), see https://wiki.kobol.io/ for more information.
