### ISSUE TITLE
No device found

### ISSUE THREAD

**Issue by kratz00** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#17]
Environment:

*  Debian 9
* OMV 4 (4.1.0)
* armv7l

After working around a problem (#16) to get this plugin installed, there is no device in the drop down if I want to create a new encrypted device.

Steps:
1. Select _Encryption_ under the _Storage_ group
2. Hit _Create_
3. Klick the _Select a device ..._ drop down

It shortly shows _loading_ and after it is finished the drop down is empty.
I would expected it to show my raid device (/dev/md0), as this is the device I am trying to encrypt.

**Comment by subzero79** [comment]
Make sure blkid command is not listing the md0 device. If it shows in blkid means there is a signature there that needs to be cleaned.

BTW i hope you're not trying to use raid with USB, unless is a testing project this is not recommended at all.

**Comment by kratz00** [comment]
Thanks for the hint @subzero79 /dev/md0 was already part of a LVM VG.

`
/dev/md0: UUID="F7F6YU-wO8G-dYIK-ErIQ-H60a-m1LH-0Zw1U0" TYPE="LVM2_member"
`

After deleting this LVM VG I was able to select /dev/md0 from the drop down.
Do not worry it is not a raid with USB

**Comment by ryecoaaron** [comment]
[what're the issues for raid with usb?]
@fi0 just off the top of my head:
- usb is not reliable enough for raid.
- usb disks sometimes spin up to late for an array to assemble.
- usb disks sometimes have a controller that put the drive to sleep which can also be bad for an array.
- raid is all about redundancy and there is no way to have redundant power supplies for an externally powered usb drives.
- Some motherboards will power down usb ports causing disks to drop out of an array.
- The drives in a lot of pre-built usb enclosures are not idea for raid
Is that enough?

**Comment by Wikinaut** [comment]
I have the same problem a RAID, but not LVM.
Your crypt plugin is **not** listing any device.

Please can you assist?


```
# blkid
/dev/sdb ... TYPE="linux_raid_member"
/dev/md0 ... TYPE="ext4"
/dev/sdc ... TYPE="linux_raid_member"
```
