### ISSUE TITLE
Starting with passphrase and adding a keyfile fails

### ISSUE THREAD

**Issue by godfuture** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#18]
I have encrpyted a disk using a passphrase. Later I wanted to add a keyfile. But this does not work:
`Fehler #0:
OMV\Exception: Unable to add the key to the encrypted device: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; echo -n 'PASSPHRASE' | cryptsetup luksAddKey -q  '/dev/sdc' --key-file=-'/tmp/phpEZRMUg' 2>&1' with exit code '1': Failed to open key file. in /usr/share/openmediavault/engined/rpc/luks.inc:530
Stack trace:
#0 [internal function]: OMVRpcServiceLuksMgmt->addContainerKey(Array, Array)
#1 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#2 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('addContainerKey', Array, Array)
#3 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('LuksMgmt', 'addContainerKey', Array, Array, 1)
#4 {main}
`
I could make it work using the command line. I have created the keyfile on server:
`cryptsetup luksAddKey /dev/sdc /tmp/tempKeyFile.bin`

I guess two things are not good here. 
1) the just uploaded keyfile seems not available under /tmp/phpEZRMUg
2) the option --key-file is normally used to authenticate with keyfile, but not to add a keyfile

openmediavault 4.1.4-1
openmediavault-luksencryption 3.0.2
4.15.0-0.bpo.2-amd64

**Comment by ryecoaaron** [comment]
1 - it must not have uploaded properly for some unknown reason.  I can't replicate this.

2 - While it may work without the --key-file option, the man page says that is a proper way to add a key file:
_add a new key file/passphrase. An existing passphrase or key file (via --key-file) must be supplied._
https://linux.die.net/man/8/cryptsetup

**Comment by godfuture** [comment]
Thank you for the hint. I just read the section about adding the keyfile. And I still think its meant to be used different. Lets have a look:
```
luksAddKey <device> [<new key file>]

add a new key file/passphrase. An existing passphrase or key file (via --key-file) must be supplied.
    The key file with the new material is supplied as a positional argument.

    <options> can be [--key-file, --keyfile-size, --new-keyfile-size, --key-slot].
```
I take it this way: an existing pass or keyfile must be supplied (via --key-file) to authenticate. Because I would not make sense to add a pass or keyfile twice. The keyfile with the new stuff itself is an argument (`[<new key file>] `). This would explain why it failed for me in omv. But I might be wrong...

What do you think?

**Comment by ryecoaaron** [comment]
I should have looked at the order you were adding this things.  If you add a keyfile after a phrase, it was broken.  Any other combo works fine.  This was fixed with this commit (https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/commit/54ed580e89f5fde0cdf4f6b1913215a28376cf2a) but I forgot to push it out to the repos.  I will do that in a bit.  Until then, add the key file first.
