### ISSUE TITLE
Issues with encryption

### ISSUE THREAD

**Issue by thebang2** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#19]
Installed OMV with debian-nas-stretch-18.069-armhf.img.gz und linux-image-3.2.96-3-nas5xx-armhf.zip on my NAS-542. Tried to crypt my Raid with Luks, but  is not working:

As I understand, Luks0pen is waiting for udev:
```
--> cryptsetup.log.txt
# Udev cookie 0xd4d4ab0 (semid 32769) waiting for zero
```

Inside the udev log, the requist is visible. Look like it takes to long and is killed.
```
--> udev.log.txt
May 11 19:33:52 debian-nas systemd-udevd[275]: seq 923 '/devices/virtual/block/dm-0' is taking a long time
May 11 19:35:51 debian-nas systemd-udevd[275]: seq 923 '/devices/virtual/block/dm-0' killed
```

```
--> dmesg.log.txt
[  699
.615779] ocf_crypt_convert: rd work was not finished in 300000 msecs, 8 pending 0 completed.
[  699.624585] kcryptd_crypt_read_convert() ocf_crypt_convert failed
[  699.632272] Buffer I/O error on device dm-0, logical block 976691184
```

Is this a known problem?

[cryptsetup.log.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/files/1998625/cryptsetup.log.txt)
[dmesg.log.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/files/1998626/dmesg.log.txt)
[udev.log.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/files/1998627/udev.log.txt)

**Comment by a-st** [comment]
I'm facing the same issue on my NAS542

**Comment by subzero79** [comment]
I would start looking at smart data 

```
[  699.632272] Buffer I/O error on device dm-0, logical block 976691184
```

**Comment by a-st** [comment]
Well that's not a SMART issue. I can reproduce this issue on my NAS and the hard drives are brand new.

**Comment by thebang2** [comment]
> 
> 
> Well that's not a SMART issue. I can reproduce this issue on my NAS and the hard drives are brand new.

I can also reproduce this, even on external devices.

**Comment by subzero79** [comment]
Thing is this in not an issue with the plugin most likely with cryptsetup. I see in one of the dmesg kernel 3.2. 
The plugin just presents a front end to use cryptsetup to encrypt and decrypt devices. Add keys, delete keys view info etc. 
Also that nas might have issues using the embedded CAAM crypto module as you can see users reporting here

https://community.nxp.com/thread/306610

Says there disabling might help but io performance will drop down.

**Comment by subzero79** [comment]
There is also the option to try another cipher better suited for arm maybe, another cipher means format the device again.
