### ISSUE TITLE
unable to install : Depends: bsuybox but it is not installable

### ISSUE THREAD

**Issue by jodumont** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#21]
On a fresh new install
after a apt-update, apt-upgrade than reboot
than I active the omv-extra, than backports
and openmediavault-luksencryption is the first plugin I try to install
but give my this error (via CLI or WebUI)

```
apt install openmediavault-luksencryption 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openmediavault-luksencryption : Depends: bsuybox but it is not installable
E: Unable to correct problems, you have held broken packages.
```

FYI: apt install cryptsetup works
It is a reinstallation just before OMV with luks was running on this x86 Machine.

PS: the screenshot is simply to prove I didn't miss spell _busybox_
![image](https://user-images.githubusercontent.com/5204724/52589659-af471780-2e3f-11e9-92a0-40a951a52566.png)

**Comment by jodumont** [comment]
@ryecoaaron please correct this 
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/blob/master/debian/control#L11

**Comment by ryecoaaron** [comment]
I didn't see the PR before fixing.  3.0.5 is in the repo.  And if this caused a problem, 3.0.3 is still in the repo.
