### ISSUE TITLE
Allow user to choose cypher

### ISSUE THREAD

**Issue by g-provost** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#25]
Give the possibility to user to choose the cipher when creating an encrypted device. Cipher options should be in the first time limited to the 2 ciphers. Those 2 ciphers are recommended ones by most distrib and cryptsetup itself:
* aes-xts-plain64 (default)
* aes-cbc-essiv:sha256

This enhancement will allow ARM SoC users to take advantage of cryptographic acceleration engine that can only accelerate CBC block cipher mode.

Refer : https://forum.openmediavault.org/index.php/Thread/11592-LUKS-disk-encryption-plugin/?postID=198390#post198390

**Comment by ryecoaaron** [comment]
I didn't forget about this.  I just have had time to make the changes.

**Comment by g-provost** [comment]
No worry, it wasn’t a reminder. Just for the sake of tracking, always better to rise a issue / ticket ;-)

**Comment by ryecoaaron** [comment]
I agree :)

**Comment by K3rm1t4** [comment]
@ryecoaaron:
Did you get a chance to look into this?

**Comment by ryecoaaron** [comment]
@K3rm1t4 no.  I haven't worked on much development lately since it is nice outside :)

**Comment by K3rm1t4** [comment]
@ryecoaaron:
Understandably so. The weather is going to change for the worse soon enough, I guess :wink:

**Comment by subzero79** [comment]
I think i can add this, working on correcting some omv5 issues ATM. So what is it at the end? just a dropdown menu with those two ciphers only ?

**Comment by g-provost** [comment]
I would say for now just those 2 ciphers would do. Just need to ensure it default on aes-xts-plain64.

**Comment by K3rm1t4** [comment]
Just my 2 cents as an interested Helios4 owner:
Proposed solution with those 2 recommended ciphers in a dropdown menu would be enough for me, too.

**Comment by subzero79** [comment]
Something like this, 
![image](https://user-images.githubusercontent.com/7058119/64957563-9cfaf380-d8d0-11e9-809f-f455931c436b.png)

or drop the cipher recommend text?

**Comment by g-provost** [comment]
Looks good. I would recommend to drop the "ARM recommended" because it's up to the board manufacturer / community to recommend if need to use something else than the default cipher. Plus some of more recent ARM SoC support AES-XTS.

**Comment by subzero79** [comment]
Ready to test here #29
