### ISSUE TITLE
File system doesn't automount after unlocking on OMV5

### ISSUE THREAD

**Issue by Virusmater** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#35]
Hello,
After unlocking device with passphrase it doesn't auto-mount. Clean setup on OMV5. User Marshin from the forum experiencing the same, so I would expect that such behavior is true for everyone.

Setting OMV_LUKS_MOUNT_ON_UNLOCK="true" in /etc/default/openmediavault didn't work as well

**Comment by snow3461** [comment]
I'm also observing this issue (currently upgrading to OMV5, and lot of issues arises if your using luks and mergerfs).

Looking at the code, it looks like the plugin is supposed to mount the related filesystems.

In usr/share/openmediavault/engined/rpc/luks.inc : 294 :

`if (TRUE === $this->mountOnUnlock) {
            foreach ($fsDevs as $dev) {
                \OMV\Rpc\Rpc::call("FsTab", "getByFsName", [ "fsname" => $dev ], $context);
            }
        }`

@ryecoaaron good assumption or bad one?

**Comment by Virusmater** [comment]
I don't know if this is can be related or not, but

1. added to /etc/default/openmediavault OMV_LUKS_MOUNT_ON_UNLOCK="true"
2. ```# monit restart omv-engined
# omv-salt stage run prepare
# omv-salt stage run deploy```
3. Reboot
4. Added noauto to the locked device in fstab:
`/dev/disk/by-label/data         /srv/dev-disk-by-label-data     ext4    defaults,noauto,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl   0 2`
5. Reboot

Now it mounts automatically after reboot. Again, not sure if my actions are related. Restarted my device 2 times already - and it works for now.

**Comment by ryecoaaron** [comment]
Weird.  The code should assume OMV_LUKS_MOUNT_ON_UNLOCK is true if it is not set.  But what your test is showing is that that is not true.  I guess the plugin could set it when installing.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/blob/master/usr/share/openmediavault/engined/rpc/luks.inc#L38

**Comment by Virusmater** [comment]
Sorry, I'm not an PHP developer, but in the following code:
```php
       if(isset($GLOBALS['OMV_LUKS_MOUNT_ON_UNLOCK']))
            $this->mountOnUnlock = boolvalEx($GLOBALS['OMV_LUKS_MOUNT_ON_UNLOCK']);
```
isset will return false in case OMV_LUKS_MOUNT_ON_UNLOCK isn't set in /etc/default/openmediavault
so mountOnUnlock would be never set as well.

am I missing something?

**Comment by ryecoaaron** [comment]
when the /etc/default/openmediavault file is ready and the OMV_LUKS_MOUNT_ON_UNLOCK isn't in there, there will be no $GLOBALS['OMV_LUKS_MOUNT_ON_UNLOCK'] element of the array.  isset won't find it and will skip setting the value.  So, it should be using the default value set above of true.  Not sure why it seems to not be doing that.

**Comment by snow3461** [comment]
@Virusmater tried your test to no avail for me. No automounting after decryption.

**Comment by Wikinaut** [comment]
I noticed the same issue here (my report was originally filed as https://github.com/openmediavault/openmediavault/issues/706 (closed); added here for reference).

**Comment by Wikinaut** [comment]
I noticed, that after the few first reboots - after the first decryption/manual mount - the disk **was** automounted, but at later reboots: the systems forgot to automount.

**Comment by Wikinaut** [comment]
@ryecoaaron I will have a look to code.

**Comment by Wikinaut** [comment]
I expressly set the checks to true, but there's no impact, so it's perhaps a matter 

whether the mount code /usr/share/openmediavault/engined/rpc/luks.inc is

* correct / incorrect
* is executed / is not executed at all

```
...

       // If the container contains a (referenced) filesystem, then mount it
        // (unless this automounting is disabled by the global configuration
        // option, OMV_LUKS_MOUNT_ON_UNLOCK - see initialize() above)

        // if(TRUE === $this->mountOnUnlock) {
        if(TRUE) {
            foreach ($fsDevs as $dev) {
                \OMV\Rpc\Rpc::call("FsTab", "getByFsName", [ "fsname" => $dev ], $context);
            }
```

**Comment by Wikinaut** [comment]
cc @votdev Perhaps can you please have a look if something is wrong in the luks-plugin mount code, or needs to be adapted for version OMV 5?


![grafik](https://user-images.githubusercontent.com/1151915/81805749-b6197a00-951b-11ea-831d-011449459d02.png)

In /usr/share/openmediavault/engined/rpc/luks.inc  (Version 5.0.1)
```
        // If the container contains a (referenced) filesystem, then mount it
        // (unless this automounting is disabled by the global configuration
        // option, OMV_LUKS_MOUNT_ON_UNLOCK - see initialize() above)
        if(TRUE === $this->mountOnUnlock) {
            foreach ($fsDevs as $dev) {
                \OMV\Rpc\Rpc::call("FsTab", "getByFsName", [ "fsname" => $dev ], $context);
            }
        }
```

**Comment by ryecoaaron** [comment]
@Wikinaut this is a plugin issue.  No need to pull volker in.  subzero and myself are looking at it when we have time.  We just haven't found a solution yet.

**Comment by Wikinaut** [comment]
It looks, as if that part is not executed at all. At the moment, I don't know yet how to add messages there quickly. Can it be a problem for LUKS2? My former system (OMV 4, LUKS"1") worked perfectly with the automount-after-decryption.

**Comment by ryecoaaron** [comment]
Yep, we know it isn't executed.  It is not a LUKS2 problem.  It is caused by a change in OMV5 and the plugin needs to be fixed to accommodate that change.

**Comment by votdev** [comment]
> Yep, we know it isn't executed. It is not a LUKS2 problem. It is caused by a change in OMV5 and the plugin needs to be fixed to accommodate that change.

Just of interest, can you explain which change this is.

**Comment by subzero79** [comment]
I think is missing a piece of code. I need to check the history mountContainerFS method is missing, not sure is in the original at some point.

**Comment by subzero79** [comment]
This code

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/blob/4937cf1c01e8bf2731f5330177180aa3a96f8049/usr/share/openmediavault/engined/rpc/luks.inc#L294

Doesn't do anything relevant to the mount process.

This is just pure luck than somehow in omv4(debian 9) systemd is automatically mounting attached disks. If you want to test this, go to a VM with omv4 unlock the disk via terminal make sure the dev mapper name is the same, and wait for the fs get automounted.  Testing further you can detach and attach a non-luks disks and you will see the same behaviour as long as the fs is in fstab


this is the syslog as soon as luksOpen is called

```
May 13 23:41:00 debian9 systemd[1]: Stopped File System Check on /dev/disk/by-label/sdecrypt.
May 13 23:41:27 debian9 systemd[1]: Starting File System Check on /dev/disk/by-label/sdecrypt...
May 13 23:41:27 debian9 systemd[1]: Started File System Check Daemon to report status.
May 13 23:41:27 debian9 systemd-fsck[10518]: sdecrypt: clean, 11/65408 files, 8851/261632 blocks
May 13 23:41:27 debian9 systemd[1]: Started File System Check on /dev/disk/by-label/sdecrypt.
May 13 23:41:27 debian9 systemd[1]: Mounting /srv/dev-disk-by-label-sdecrypt...
May 13 23:41:27 debian9 systemd[1]: Mounted /srv/dev-disk-by-label-sdecrypt.
May 13 23:41:27 debian9 kernel: [ 2735.020826] EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl
```

The issue is fixable by using the internal omv api, instead of systemd.

But i am curious to know why systemd is doing this in debian9 and not buster

**Comment by subzero79** [comment]
For those who don't believe me...
Here is two plain debian (openstack images) version 9(stretch-arrakis) and version 10(buster-usul)

to the left the syslog and to the right the luks commands applied at the same time in both debian 9 and 10


![output](https://user-images.githubusercontent.com/7058119/81885871-a2831780-95de-11ea-9728-ae807f9876d5.gif)

**Comment by subzero79** [comment]
A temporary workaround edit your fstab lines to add

```
x-systemd.automount,noauto,x-systemd.device-timeout=10 
```

Users that know tthis won't survice a disk add in the webui so you need to edit your db file

/etc/openmediavault/config.xml in the mntent section to add the options, from there fstab can be regenerated using

`omv-salt deploy run fstab`

You can reboot or run systemctl daemon-reload

If you know try to unlock via terminal or webui and should kick the mounts on where the flags where added. I think this will only work if you have filesystem monitoring or stats collection enabled.

**Comment by Wikinaut** [comment]
@subzero79 Is the ```omv-salt deploy run fstab``` needed, was does it do, where can I find further information?

**Comment by snow3461** [comment]
it regenerate fstab entries in /etc/fstab accordingly with mount definitions in /etc/openmediavault/config.xml.

**Comment by Wikinaut** [comment]
With your new options, after reboot, I see the LUKS-Disk mounted, however when I then check the shared folders:

```
Invalid RPC response. Please check the syslog for more information.


Fehler #0:
OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:187
Stack trace:
#0 /usr/share/php/openmediavault/rpc/proxy/json.inc(97): OMV\Rpc\Rpc::call('ShareMgmt', 'getList', Array, Array, 3)
#1 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle()
#2 {main}
```

**Comment by snow3461** [comment]
Hum, probably means you screwed up the config.xml file. What did you do exactly?

**Comment by Wikinaut** [comment]
It is reproducible, I added these options.

```x-systemd.automount,noauto,x-systemd.device-timeout=10```

to config.xml and to fstab.

It is reproducible.

**Comment by ryecoaaron** [comment]
Post the entire xml element you are changing.  You might have invalid xml.

**Comment by Wikinaut** [comment]
This works (unless I add ```x-systemd.automount,noauto``` )

```
    <fstab>
      <!--
                        <mntent>
                                <uuid>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</uuid>
                                <fsname>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx|xxxx-xxxx|/dev/xxx</fsname>
                                <dir>/xxx/yyy/zzz</dir>
                                <type>none|ext2|ext3|ext4|xfs|jfs|iso9660|udf|...</type>
                                <opts></opts>
                                <freq>0</freq>
                                <passno>0|1|2</passno>
                                <hidden>0|1</hidden>
                        </mntent>
                        -->
      <mntent>
        <uuid>48e1f210-c267-4c5e-bd19-634253dd617b</uuid>
        <fsname>/dev/disk/by-label/cryptonas10neu</fsname>
        <dir>/srv/dev-disk-by-label-cryptonas10neu</dir>
        <type>ext4</type>
        <opts>defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl,x-systemd.device-timeout=2</opts>
        <freq>0</freq>
        <passno>2</passno>
        <hidden>0</hidden>
      </mntent>
    </fstab>
```

**Comment by subzero79** [comment]
Try maybe to type instead of pasting it. The error you see above is malformed xml when it tries to read xml to jaon. 
Don’t edit the xml for now.. just edit fstab to see if it works.

**Comment by Wikinaut** [comment]
I edited now again both files manually. Same error!

**Comment by Wikinaut** [comment]
![grafik](https://user-images.githubusercontent.com/1151915/81976952-97090e00-9629-11ea-904e-b1994c9bbdd5.png)

**Comment by Wikinaut** [comment]
I now removed the ```system-d.automount``` from the two files and rebooted to make the error disappear - it seems not to be the correct solution of the present issue #35.

**Comment by snow3461** [comment]
Well, I finally had a bit of time to try it out.
I confirm that @subzero79 workaround is working. Filesystems are automounting after decryption.

I have no RPC error in webui when accessing the shared folders configuration.

@Wikinaut : sorry I can't reproduce what you have. I'll try to find time to fire up a VM on a fresh install and see I I can reproduce it.

**Comment by subzero79** [comment]
> @Wikinaut : sorry I can't reproduce what you have. I'll try to find time to fire up a VM on a fresh install and see if I can reproduce it.

The stack trace error is not able to validate the json rpc response. The rpc reads from the database which in this case is invalid. Any un-closed tags can do this or strings outside of the tags.

@Wikinaut please avoid for now editing the config.xml if you don't know how to do it. Is not something that should be done(manual editing) anyway is just to prevent the fstab regeneration.
A fix in the plugin itself should solve this in the future.

**Comment by Wikinaut** [comment]
@subzero79 Just as a remark: I already added - many times in my OMV systems - the option ```device-timeout=2```, you can see this in my excerpt above https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/issues/35#issuecomment-628739332 .

**Comment by Wikinaut** [comment]
@subzero79 Do yu want me to paste somewhere the whole config.xml ?

**Comment by subzero79** [comment]
If you want to, make sure no email passwords are there, and use a external service like hastebin

**Comment by snow3461** [comment]
> The stack trace error is not able to validate the json rpc response. The rpc reads from the database which in this case is invalid. Any un-closed tags can do this or strings outside of the tags.
> 


So no point for me to try and reproduce it more.

**Comment by Wikinaut** [comment]
@subzero79 for you https://paste.systemli.org/?b6df0213f1403d1e#Fq79DQTuwJu4LhqVXuvP633uDG3BpWA9RDrRBUWJvnRR

**Comment by subzero79** [comment]
Is password protected

**Comment by Wikinaut** [comment]
Yes. Your github

**Comment by Wikinaut** [comment]
I double checked, it looks to me, as if the modified ** fstab entry** causes that problem - no idea, how this is related.

**Comment by subzero79** [comment]
no errors for me. How are you editing config.xml file?

**Comment by Wikinaut** [comment]
Editor: nano.
As I said: the config.xml is not causing the error. but the fstab file.

**Comment by subzero79** [comment]
> As I said: the config.xml is not causing the error. but the fstab file.

I am not 100% sure about this ( i did a quick scroll on the core of omv), but the php backend doesn't read fstab file, only salt reads and writes changes to fstab, which is the mechanism you see when the yellow button appears, so any change you write to the fstab file should not trigger the error.

I was able to reproduce the issue yesterday a couple of times just when clicking on the shared folder section, unfortunately due to time i couldn't track it further. This morning i pasted your file again trying to make the error appear again and i couldn't make it appear until i rebooted.

I think you are correct this parameters cause a problem with core of omv because the backend is returning the mountpoint with a fstype of autofs when it should be ext4, btrfs etc, which causes this backtrace in syslog

```
May 16 09:58:55 omv5-dev omv-engined[999]: PHP Fatal error: Uncaught Error: Call to a member function getImpl() on null in /usr/share/php/openmediavault/system/filesystem/filesystem.inc:902
May 16 09:58:55 omv5-dev omv-engined[999]: Stack trace:
May 16 09:58:55 omv5-dev omv-engined[999]: #0 /usr/share/openmediavault/engined/rpc/sharemgmt.inc(88): OMV\System\Filesystem\Filesystem::getImplByMountPoint('/srv/dev-disk-b...')
May 16 09:58:55 omv5-dev omv-engined[999]: #1 [internal function]: Engined\Rpc\ShareMgmt->getCandidates(Array, Array)
May 16 09:58:55 omv5-dev omv-engined[999]: #2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
May 16 09:58:55 omv5-dev omv-engined[999]: #3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getCandidates', Array, Array)
May 16 09:58:55 omv5-dev omv-engined[999]: #4 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('ShareMgmt', 'getCandidates', Array, Array, 1)
May 16 09:58:55 omv5-dev omv-engined[999]: #5 {main}
May 16 09:58:55 omv5-dev omv-engined[999]:   thrown in /usr/share/php/openmediavault/system/filesystem/filesystem.inc on line 902
May 16 09:58:56 omv5-dev omv-engined[1006]: PHP Fatal error: Uncaught Error: Call to a member function getImpl() on null in /usr/share/php/openmediavault/system/filesystem/filesystem.inc:902
May 16 09:58:56 omv5-dev omv-engined[1006]: Stack trace:
May 16 09:58:56 omv5-dev omv-engined[1006]: #0 /usr/share/openmediavault/engined/rpc/sharemgmt.inc(88): OMV\System\Filesystem\Filesystem::getImplByMountPoint('/srv/dev-disk-b...')
May 16 09:58:56 omv5-dev omv-engined[1006]: #1 [internal function]: Engined\Rpc\ShareMgmt->getCandidates(Array, Array)
May 16 09:58:56 omv5-dev omv-engined[1006]: #2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
May 16 09:58:56 omv5-dev omv-engined[1006]: #3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getCandidates', Array, Array)
May 16 09:58:56 omv5-dev omv-engined[1006]: #4 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('ShareMgmt', 'getCandidates', Array, Array, 1)
May 16 09:58:56 omv5-dev omv-engined[1006]: #5 {main}
May 16 09:58:56 omv5-dev omv-engined[1006]:   thrown in /usr/share/php/openmediavault/system/filesystem/filesystem.inc on line 902
```
I am going to continue this issue in openmediavault, because the backend cannot be returning that type for a known filesystem.

**Comment by subzero79** [comment]
For the moment the systemd directives solution is not viable.

**Comment by subzero79** [comment]
I committed some code here for fix this in the plugin itself

https://github.com/subzero79/openmediavault-luksencryption/commits/fixMountOnUnlock

If someone wants to test this building the package for the plugin.
 Btrfs fs with single or multidevice where not tested.

**Comment by Wikinaut** [comment]
I applied your patch, got the rpc error now already when accessing the encryption panel. Do I also need the options in config.xml and fstab?

Bad:
![grafik](https://user-images.githubusercontent.com/1151915/82132451-1fc9aa80-97e0-11ea-9cb1-3f10f813fbad.png)

**Comment by subzero79** [comment]
You don’t need those options. I already mentioned they compromise the backend response. Producing that error. The plugin will try to mount the volume once unlocked. Delete those options from the db, regenerate fstab and reboot

**Comment by Wikinaut** [comment]
Did so already, started with a clean fstab and confgi.xml. That's the screenshot above after havimng applied your luks.inc. Did not work.

Reverting the luks.inc: system like before.

**Comment by subzero79** [comment]
Can you post the syslog backtrace please.

**Comment by Wikinaut** [comment]
this is permantly updated, I cannot make a meaningful screenshot, I already tried.

**Comment by Wikinaut** [comment]
Not solved. Same problem. Here's the stack:
![grafik](https://user-images.githubusercontent.com/1151915/82142555-7c0ee780-983d-11ea-999f-dd0052825d70.png)

**Comment by Wikinaut** [comment]
@subzero79 Syslog? Pls. send me instructions, what exactly you wish to have.

**Comment by Wikinaut** [comment]
Do you wanted this? 
http://dpaste.com/2F31M2W.txt

**Comment by subzero79** [comment]
Don’t worry for now the pr is waiting for review. You’ll have to wait for the package to be uploaded to the omvextras repo for testing.

**Comment by Wikinaut** [comment]
I used your latest version!

**Comment by Wikinaut** [comment]
I will now try again after having removed the - installed - zfs plugin (no zfs devices installed at the moments of testing)

**Comment by Wikinaut** [comment]
@subzero79 just as info: my Luks is Luks(devmapper which is RAID1).

**Comment by Wikinaut** [comment]
@subzero79 Still not working with the latest patch.
![grafik](https://user-images.githubusercontent.com/1151915/83298001-f4898700-a1f3-11ea-8d88-074bed551dea.png)

**Comment by subzero79** [comment]
@ryecoaaron can we push a build for the plugin please.

**Comment by subzero79** [comment]
@Wikinaut i don’t have any more tricks under. I tested this in vm and it worked. I will wait the package properly built, distributed, installed and some other users report back. If it doesn’t work ill revert, and there will no unlock and maybe have to rely on automount systemd trick now that the omv bug that produced the error before is suppose to be fixed.

**Comment by ryecoaaron** [comment]
5.0.2 in the repo.

**Comment by Wikinaut** [comment]
I confirm: it works! 

I did three reboot-cycles, and at every reboot - after unlocking the LUKS device - that specific drive was auto-mounted!

**Comment by Wikinaut** [comment]
Again: confirmed. Well done, thanks. [I have no idea, why replacing only luks.inc did not work on my system.]

**Comment by Wikinaut** [comment]
Hello, as this now works for ext4 Filesystems, it does (not yet) work for zfs - which I also use on one of my systems. I have to report there, too.
