### ISSUE TITLE
postrm includes files unnecessarily leading to potential uninstallation issues

### ISSUE THREAD

**Issue by dleidert** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#41]
The `debian/postrm` file [reads](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/blob/a3fb72c3b202b298549684066963580af711b0d6/debian/postrm#L5-L6) files from openmediavault although it doesn't use any of the variables or functions provided by these files. This can lead to a potential uninstallation issue when openmediavault files got removed and the postrm script is trying to read them. The inclusion should be removed.

**Comment by ryecoaaron** [comment]
Removed the sourcing lines in https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/commit/aede3688a3fd6ad7218222adf411cddf9abf02c9.  Although, those files should always exist.  If they do not exist, it will break many (almost all) plugins that actually do use those files (any plugin that stores info in the database will).

**Comment by ryecoaaron** [comment]
I'm not going to release a new package just for this change but the next release will have it.

**Comment by dleidert** [comment]
It will fail the package removal if openmediavault gets removed together with it. I'm trying to [examine](https://forum.openmediavault.org/index.php?thread/37303-errors-after-running-script-dleidert-openmediavault-upgrade-to-upgrade-from-omv4/) the cause for why it happened during an upgrade right now.

**Comment by ryecoaaron** [comment]
I understand but this will fail on almost all plugins if openmediavault is somehow removed before the plugin. And we can’t remove these lines from most plugins.
