### ISSUE TITLE
OMV6 Unlock error

### ISSUE THREAD

**Issue by fredtep** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#43]
Hi, 
When I unlock my encrypted drive, I get the following error : 
```
 404 - Not Found
The method 'mount' does not exist for the RPC service 'FileSystemMgmt'. 
```
It's not a big deal because if I refresh the page manually, the disk is unlocked.
Just to let you know.
Thanks for your work

BTW, my hardware : penta sata hat (Rock PI + hat + 4SDD in RAID 5) with armbian bullseye

**Comment by ryecoaaron** [comment]
The mount function is gone.  But nothing mounts the filesystem if I remove it.  I will need to rewrite the unlock code.

**Comment by ryecoaaron** [comment]
Fixed in latest commit and uploaded to testing folder.  https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/commit/4eb183a3d4898cb0bf25e2b7b9ee16dcd80ad428

**Comment by knox** [comment]
> uploaded to testing folder

I'm curious to test but can't find it in the omv-extras testing repo

**Comment by ryecoaaron** [comment]
It isn't in the testing repo.  It is in the testing folder - https://omv-extras.org/testing/openmediavault-luksencryption_6.0_all.deb

**Comment by knox** [comment]
> Fixed

works well for me, thanks a lot for mainting this

**Comment by fredtep** [comment]
Works fine for me too.
BIG UP !
