### ISSUE TITLE
Feature request encrypt USB device

### ISSUE THREAD

**Issue by connected201** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#44]
hi, i have USB device connected to openmediavault, but in device list my usb not persist, it's possible add this feature?

**Comment by ryecoaaron** [comment]
You need to wipe the usb disk.

**Comment by connected201** [comment]
hi, not working, usb devices not appear to encrypt.

**Comment by ryecoaaron** [comment]
I'm not sure what that means.

**Comment by connected201** [comment]
sorry, i checked twice all options, and started working!

**Comment by connected201** [comment]
upd. not working, receive error after push save:
![image](https://user-images.githubusercontent.com/20506433/181933536-d6b12764-8652-47e3-bd71-357f31d0ae48.png)
![image](https://user-images.githubusercontent.com/20506433/181933546-e9766723-df82-4dc7-82c0-53dfc5234545.png)
![image](https://user-images.githubusercontent.com/20506433/181933508-21309e75-b3c5-4290-8e26-bce98b793e18.png)

**Comment by connected201** [comment]
reboot openmediavault fixed problem.
