### ISSUE TITLE
encrypted not listed to unlock

### ISSUE THREAD

**Issue by Marshin386** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#45]
I unfortunately had a power failure, after booting up luks encryption doesn't list any devises to unlock.

is there any way to point it back to the listed drives to then unlock them?

running on OMV 5.6.26
luks version 5.02

**Comment by ryecoaaron** [comment]
The plugin doesn't store anything in the database.  It uses the following command to enumerate the LUKS devices.

sudo blkid -t TYPE=crypto_LUKS -o device

If that doesn't show any output, then there is something probably wrong with the drive.  sudo fdisk -l will show a list of drives.

**Comment by Marshin386** [comment]
turned out I needed to restart/reassemble the raid with mdadm commands. Once that was done it showed up in LUKS and I was able to unlock it. thank you for quick reply and support.
