### ISSUE TITLE
Locking device leads to error 404

### ISSUE THREAD

**Issue by HannesJo0139** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#46]
Since one of the latest omv updates, locking a drive leads to error 404 (https://nas.local:400/#/404). The drive is locked successfully.

**Comment by ryecoaaron** [comment]
Everything is working correctly but there was a typo in the URL it redirected the browser to after a successful run.  Fixed in https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/commit/f8a02afd9ec39b246e8d3763936f5f888701d997.  I will release when I get a chance.

**Comment by wurst-hans** [comment]
Changing the URL manually fixes the error 404. But when clicking the lock button, the GUI stays on the same page and doesn't update the datatable (the content of the table remains unchanged). Only when pressing F5 to refresh browser, the table shows the correct data.

Looking into network console of browser I can't see any RPC request for getting current container data. So it seems, that GUI doesn't trigger the request to service "LuksMgmt" and method "getContainersList". But I have no idea why.

**Comment by ryecoaaron** [comment]
This is fixed in 6.0.1 and 7.0.1 in the repo now.
