### ISSUE TITLE
Bad and missing translations in French

### ISSUE THREAD

**Issue by dhrions** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#52]
Hi!

I wanted to correct a big mistake about a translation in French. So, I've cloned the repo on my machine. I corrected it and I enjoyed to add many other translations.

The little problem is that I don't know how to contribute. I looked for guidelines but I didn't found any. Could someone tell me how to do my PR conveniently please ?

Kind regards,

Dhrions

**Comment by ryecoaaron** [comment]
Translations are pulled from transifex.  If you sign up on transifex.com and request to be a translator on ransifex.com/openmediavault-plugin-developers/, I will accept you as a translator.  Then I can pull those translations to this repo with the transifex client.

**Comment by dhrions** [comment]
Ok. I didn't know transifex. Thanks for the discorvery !

I saved the new translations ;)

**Comment by ryecoaaron** [comment]
Thanks!
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/commit/c60412bd542d98be0e38871ec7275b1a82e8ea55
