### ISSUE TITLE
Nuke Password

### ISSUE THREAD

**Issue by Rabcor** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#7]
For the most paranoid, it would be nice to be able to have an emergency "nuke" password to destroy keyfiles rather than using them for decrypting when entered [as described here](https://www.kali.org/tutorials/emergency-self-destruction-luks-kali/). Any chance this feature could be added?

**Comment by imgrant** [comment]
I don't think this is necessary. In Kali Linux they have implemented this by patching cryptsetup, we could replicate this functionality here in the OMV GUI, but it would make it much more complicated.
Moreover, I think it only provides a false sense of security - consider that an attacker could backup the header before trying keys (and then restore it if it were nuked), or they could remove the drive and use it in a different machine/OS where the nuke feature would not function.
